# <center> <span style='color:#23689B'>Ejercitación durante teoría</span></center>

Módulo 6 - Parte teórica

**Profesor Adjunto:** Mag. Bioing. Baldezzari Lucas

<p style='text-align: left;'> V2022 </p>

<hr style="border:1px solid gray"> </hr>

<hr style="border:1px solid #16C79A"> </hr>

## <span style='color:#16C79A'>1. Trabajando con matrices de Sodoku</span>

Dispone de dos listas que se muestran debajo.

In [1]:
juegoSodoku= [[0, 0, 4, 3, 0, 0, 2, 0, 9],
             [0, 0, 5, 0, 0, 9, 0, 0, 1],
             [0, 7, 0, 0, 6, 0, 0, 4, 3],
             [0, 0, 6, 0, 0, 2, 0, 8, 7],
             [1, 9, 0, 0, 0, 7, 4, 0, 0],
             [0, 5, 0, 0, 8, 3, 0, 0, 0],
             [6, 0, 0, 0, 0, 0, 1, 0, 5],
             [0, 0, 3, 5, 0, 8, 6, 9, 0],
             [0, 4, 2, 9, 1, 0, 3, 0, 0]]

solutionSodoku =   [[8, 6, 4, 3, 7, 1, 2, 5, 9],
                   [3, 2, 5, 8, 4, 9, 7, 6, 1],
                   [9, 7, 1, 2, 6, 5, 8, 4, 3],
                   [4, 3, 6, 1, 9, 2, 5, 8, 7],
                   [1, 9, 8, 6, 5, 7, 4, 3, 2],
                   [2, 5, 7, 4, 8, 3, 9, 1, 6],
                   [6, 8, 9, 7, 3, 4, 1, 2, 5],
                   [7, 1, 3, 5, 2, 8, 6, 9, 4],
                   [5, 4, 2, 9, 1, 6, 3, 7, 8]]

#### Ejercicio 1.1

A partir de las listas *juegoSodoku* y *solutionSodoku* debe,

- Importar numpy como np
- Convertir las listas mencionadas en *ndarray* como enteros de 8 bits.
- Imprimir en pantalla las dimenciones y la cantidad de bytes que ocupan cada array.

In [3]:
## Ejercicio 1.1
## TODO
import numpy as np
list1= np.array(juegoSodoku, dtype = np.int8)
list2= np.array(solutionSodoku, dtype= np.int8 )
print(list1.shape, list1.nbytes)
print(list2.shape, list2.nbytes)

(9, 9) 81
(9, 9) 81


#### Ejercicio 1.2

Crear un array 3D llamado juegoSol a partir de los dos array previamente creados. Imprimir las dimensiones del array para chequear que sean de tres dimensiones.

In [5]:
## Ejercicio 1.2
## TODO

juegoSol = np.array([juegoSodoku, solutionSodoku])
juegoSol.shape

(2, 9, 9)

#### Ejercicio 1.3

- Cree un array que contenga valores de 5 a 10 con 50 valores equiespaciados.
- Cree un array que contenva valores de 0 a 100 inclusive separados de a 2.

In [ ]:
## Ejercicio 1.3
## TODO

<hr style="border:1px solid #16C79A"> </hr>

## <span style='color:#16C79A'>2. Chopeando señales y calculando tiempos de ejecición</span>

A) Cargue en una lista la señal de fotoplestimografía vistas en clases anteriores, a partir de esta genere otra lista formada por trozos de duración de dos segundos a partir de la señal original. Para llevar a cabo lo solicitado utilice blucles *for* y con *%%time* mida el tiempo que le lleva hacer esto.

B) Realice lo mismo que el punto A pero esta vez cargue los datos de la señal de fotoplestimografía en un numpy.array y utilice reshape() para redimensionar el array original con trozos con una duración de $2$ segundos. Utilice la función *%%time* para medir el tiempo de ejecución de esta segunda implementación.

##### Ejemplo uso %%time

Si quisieramos medir el tiempo que le lleva (en una PC en particular) a Python para recorrer un array de un millon de valores y elevar al cuadrado cada elemento podríamos hacer en una celda de Jupyter Notebook lo siguiente en una celda,

```Python
%%time
lista = [*range(1,1000000)]
for i in range(len(lista)):
    lista[i]**2
```

In [22]:
%%time
file = open("plethysmography.txt", "r")
leListe = [float(valor) for valor in file.read().split()]
lista1= [a for a in leListe[:int((len(leListe)*(1/125)/4))]]
print(lista1)




[0.43597, 0.43206, 0.42815, 0.42424, 0.42131, 0.41838, 0.4174, 0.41642, 0.41544, 0.41447, 0.41251, 0.41153, 0.40958, 0.40762, 0.40665, 0.40665, 0.40665, 0.40762, 0.4086, 0.4086, 0.41056, 0.41153, 0.41153, 0.41056, 0.4086, 0.40665, 0.40469, 0.40469, 0.40567, 0.4086, 0.41251, 0.42033, 0.43206, 0.45259, 0.4741, 0.4956, 0.51808, 0.5347, 0.55034, 0.56403, 0.57576, 0.58456, 0.59238, 0.59629, 0.59922, 0.60117, 0.60215, 0.60313, 0.60313, 0.60117, 0.59824, 0.59335, 0.58553, 0.57771, 0.57185, 0.56207, 0.54741, 0.53372, 0.52102, 0.50929, 0.50244, 0.49756, 0.4956, 0.49462, 0.49365, 0.49365, 0.49365, 0.49169, 0.48876, 0.4868, 0.48387, 0.48094, 0.47801, 0.47507, 0.47116, 0.46823, 0.46334, 0.45846, 0.45357, 0.44868, 0.44379, 0.43891, 0.435, 0.43109, 0.4262, 0.42326, 0.42033, 0.41838, 0.41642, 0.41447, 0.41447, 0.41349, 0.41251, 0.41251, 0.41251, 0.41251, 0.41251, 0.41349, 0.41544, 0.4174, 0.41935, 0.42033, 0.42131, 0.42131, 0.42033, 0.41935, 0.41642, 0.41447, 0.41349, 0.41349, 0.41642, 0.42131, 0.428

In [16]:
## TODO B)

<hr style="border:1px solid #16C79A"> </hr>

## <span style='color:#16C79A'>3. Censo de arboles de Nueva York</span>

Suponga que esta haciendo un trabajo de investigación con datos del [censo de arboles de la ciudad de Nueva York](https://www.nycgovparks.org/trees/treescount). Usted dispone de un archivo llamado *tree_census.npy* (el cual se carga en la siguiente celda). A fines práctico, el set de datos corresponde a una pequeña parte de los [datos originales](https://www.kaggle.com/datasets/nycparks/tree-census).

Cada fila dentro de los datos del archivo *tree_census.npy* corresponde a un arbol diferente. Cada columna representa, de izquierda a derecha,

- ID del arbol.
- ID del bloque donde se encuentra.
- Diámetro del tronco.
- Diámetro de tronco *cortado*.

Es importante el orden de las columnas, ya que Numpy no tiene información acerca de los nombres de las columnas (esto lo solucionaremos con Pandas).

A continuación se carga el archivo *tree_census.npy* y se muestran la información de los primeros 5 arboles.

In [1]:
import numpy as np
with open("files/tree_census.npy", "rb") as f:
    treeInfo = np.load(f)

print(treeInfo[:5,:])

[[     3 501451     24      0]
 [     4 501451     20      0]
 [     7 501911      3      0]
 [     8 501911      3      0]
 [     9 501911      4      0]]


**Nota:** Los valores *0* en la última columna, pertenecientes a los diametros de troncos cortados (sutump trunks) corresponden a arboles vivos, de ahí que sus diametros sean ceros.

##### Ejercicio 3.1

En esta primera parte se trabajará solamente con la segunda columna del set de datos, la cual representa el ID del bloque. 

Se le pide,

- Seleccione todas las columnas correspondientes a la columnda de los IDs de bloques.
- Imprima los primeros 4 IDs.

In [2]:
## TODO Ejercicio 3.1
data= treeInfo[:,1]
print(data[:4])

[501451 501451 501911 501911]


- Seleccione el 10mo ID dentro de bloquesIDs.
- Imprima el ID.

In [3]:
## Seleccione el 10mo ID dentro de bloquesIDs
print(treeInfo[9,1])

501911


- Realice un slice de cinco IDs de bloque a partir de bloquesIDs, empezando con el 10mo bloque.
- Imprima el slice realizado.

In [4]:
print(treeInfo[10:16,1])

[501911 501911 501909 501909 501909 501909]


##### Ejercicio 3.2

Ahora se trabajará con la columna de los dipametros de troncos.

- Cree un array que contenga los primeros 100 diametros de tronco del set de datos en *treeInfo*.
- Cree un array con los diametros de tronco desde el 50 hasta el 100 (incluyéndolo) correspondientes a las filas pares dentro de *treeInfo*.

In [5]:
diam= np.array(treeInfo[:100,2])
print(diam)
diam= np.array(treeInfo[50:101:2,2])
print(diam)

[24 20  3  3  4  4  4  4  4  3  3  4  2  2  3  4  4  4  0 14  3  4  7  8
  7  8  7  5  6  5  5 17  0 19 21 18  4  5  3  4  3  4 13 13 13  5  4  4
  4 11  5  4  5  8 51  7  4 15  3  8  6  6  3  4  3  2  3  3  6  5  5  5
  5  9  4  4  7  7  6  5  4  4  5  5  5  7  3  5  3  3  6  6  8  7  4  5
  4  4  4  4]
[ 5  5 51  4  3  6  3  3  3  6  5  5  4  7  6  4  5  5  3  3  6  8  4  4
  4  6]


##### Ejercicio 3.3

Utilizando la función [*numpy.sort()*](https://numpy.org/doc/stable/reference/generated/numpy.sort.html) cree una nueva matriz que contenga los datos de *treeInfo* ordenados de menor a mayor considerando los diámetros de los troncos.

In [9]:
sortedByTrunks = np.sort(np.array(treeInfo[:,2]))
print(sortedByTrunks)

[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  1  1  1  1  1  1  2  2  2  2  2  2
  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2
  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2
  2  2  2  2  2  2  2  2  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3
  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3
  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3
  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  4  4  4  4
  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4
  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4
  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4
  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4
  4  4  4  4  4  4  4  4  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5
  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5

### <span style='color:#F5A211'>Filtrando datos</span>

##### Ejercicio 3.4

- Usando indexación Booleana, cree un array que contenga los datos de la fila completa de *treeInfo* correspondiente al arbol con diametro de tronco igual a 51.

In [11]:
mask = treeInfo[:,2] == 51
infoTronco51 = treeInfo[mask]
infoTronco51

array([[    61, 501882,     51,      0]], dtype=int64)

- A partir de la info extraída del arbol con diámetro de tronco igual a 51 genere un slice que contenga sólo el ID de dicho arbol.

In [13]:
IDBlockTronco51 = infoTronco51[:,1]
IDBlockTronco51

array([501882], dtype=int64)

- Utilizando *fancy indexing* cree un array que contenga todos los arboles que poseean el mismo ID de bloque que el arbol con diámetro de tronco igual a 51.

In [14]:
mask = ___
arbolesCerca51 = ___

- Genere una matriz que contenga los IDs y los diámetros de tronco correspondientes a los árboles con diámetros entre 20 y 51 inclusive.

In [15]:
shortTreeInfo = ___

##### Ejercicio 3.5 - Fancy indexing vs np.where()

- Usando filtrado por máscara (fancy indexing) cree un array el cual contenga solamente datos de los arboles del bloque 313879.

- Usando np.where() cree un array de índices para los arboles con ID de bloque igual a 313879. Luego utilice este arreglo de índices para crear un array que contega información de los arboles del bloque 313879.

In [16]:
## TODO - Ejercicio 3.5

##### Ejercicio 3.6 - Reemplazando datos en el array

- Crear e imprimir un array 1D el cual reemplace los diámetros de tronco por los diametros de tronco cortado (stump trunk) en el caso de que el diámetro del tronco sea cero.

*Hint*: Utilice np.where().

<hr style="border:1px solid #16C79A"> </hr>

## <span style='color:#16C79A'>4. Summarizing datos de un array</span>

Para este ejercicio se trabajará con un pequeño data set correspondientes a las ventas mensuales, desde enero a diciembre de tres industrias diferentes. Cada fila es una *venta mensual* correspondiente a un mes para cada industria. La primer columna corresponde a industria de bebida, la segunda a restaurantes y la tercera a shoppings.

En la siguiente celda se cargan los datos en un array llamado *ventasAnuales*.

In [12]:
import numpy as np

ventasAnuales = np.array(  [[ 4134, 23925,  8657],
                           [ 4116, 23875,  9142],
                           [ 4673, 27197, 10645],
                           [ 4580, 25637, 10456],
                           [ 5109, 27995, 11299],
                           [ 5011, 27419, 10625],
                           [ 5245, 27305, 10630],
                           [ 5270, 27760, 11550],
                           [ 4680, 24988,  9762],
                           [ 4913, 25802, 10456],
                           [ 5312, 25405, 13401],
                           [ 6630, 27797, 18403]])

##### Ejercicio 4.1 - Ventas totales en cada mes

- Obtenga un array 2D que este formado por una sola columna con las ventas de cada industria en cada mes. Llame a este array *ventasMensuales*. 
- A partir de *ventasMensuales* agregue una columna al array *ventasMensuales* utilizando *numpy.concatenate()* y guarde esta nueva matriz en una variable llamada *ventasMenYTotales*.

*Hint*: Utilice *keepdims = True* en su función.

In [18]:
ventasMensuales = ___
ventasMenYTotales = ___

##### Ejercicio 4.2 - Promedio de ventas

- Crear un array 1D llamado promedioVenMensuales que contenga el promedio de ventas de cada industria en los 12 meses.
- Crear un array 1D llamado promedioVenShopping que contenga las ventas mensuales de los shopings.

In [19]:
promedioVenMensuales = ___
promedioVenShopping = ___

## Descomente las lineas para graficar
# import matplotlib.pyplot as plt
# plt.plot(np.arange(1,13), promedioVenMensuales, label="Promedio de ventas para cada industria")
# plt.show()
 
## Plot department store sales by month
# plt.plot(np.arange(1,13), promedioVenMensuales[:,2], label="Department store sales")
# plt.legend()
# plt.show()

##### Ejercicio 4.3 - Suma acumulada

- Genere un array llamado *ventasAcumuladas* que contenga las sumas acumuladas de las ventans mensuales de cada industria a lo largo de todo el año.

In [20]:
ventasAcumuladas = ___

# ## Descomente las lineas para graficar
# plt.plot(np.arange(1, 13), ventasAcumuladas[:,0], label="Tiendas de bebida")
# plt.plot(np.arange(1, 13), ventasAcumuladas[:,1], label="Restaurantes")
# plt.plot(np.arange(1, 13), ventasAcumuladas[:,2], label="Shoppings")
# plt.legend()
# plt.show()

- Cree un array 2D llamado *impuestos* que sea el resultado de multiplicar cada elemento del array *ventasAnuales* por $0.05$.
- Imprima los impuestos pagados por los restaurantes en los meses que van de febrero a julio.

In [21]:
impuestos = __

- Cree un array 2D llamado *totalesAnuales* que sea el resultado de sumar *ventasAnuales* e *impuestos* .

### <span style='color:#F5A211'>Proyectando ventas</span>

Se dispone de una lista llamada *listaMulti* que contiene valores correspondientes a las proyecciones de venta para los meses del siguiente año de cada industria.

Por ejemplo, un valor de 0.98 en enero para la industria de bebidas indica que se espera tener un 98% de las ventas de enero acutal en enero del año que viene.

In [22]:
listaMulti =   [[0.98, 1.02, 1.],
               [1.00, 1.01, 0.97],
               [1.06, 1.03, 0.98],
               [1.08, 1.01, 0.98],
               [1.08, 0.98, 0.98],
               [1.1 , 0.99, 0.99],
               [1.12, 1.01, 1.  ],
               [1.1 , 1.02, 1.  ],
               [1.11, 1.01, 1.01],
               [1.08, 0.99, 0.97],
               [1.09, 1.  , 1.02],
               [1.13, 1.03, 1.02]]

##### Ejercicio 4.4

- Cree un array llamado *multiplicadores* a partir de listaMulti. 
- Cree un nuevo array llamado *proyecciones* el cual contiene los valores de ventas proyectados resultado de multiplicar *ventasAnuales* con *multiplicadores*.

In [23]:
multiplicadores = ___
proyecciones = ___

# ## Descomente las lineas para graficar
# plt.plot(np.arange(1,13), ventasAnuales[:,1], label="Ventas actuales de restaurantes")
# plt.plot(np.arange(1,13), proyecciones[:,1], label="Ventas proyectadas de restaurantes")
# plt.legend()
# plt.show()

<hr style="border:1px solid #16C79A"> </hr>

## <span style='color:#16C79A'>5. Broadcasting entre arrays</span>

Se dene tener en cuenta que cuando queremos realizar un broadcasting a lo largo de las columnas de un array, debemos pasarle a Numpy un array 2D, ¿por qué? La razón es que debemos tener un array que contenga datos *verticales*, o lo que sería lo mismo, *un vector columna*. Cuando el shape de un array es de la forma (n,), Numpy no puede discriminar si el array es Columna o Fila, y de hecho, como hemos mencionado en teoría, Numpy por defecto toma los broadcasting de arrays a lo largo de las filas.

Por lo tanto, si quisieramos tener un vector columna de $n$ datos debemos hacer que nuestro array tenga el shape **(n,1)**.

A Python list called monthly_growth_rate with len() of 12 is available. This list represents monthly year-over-year expected growth for the economy; your task is to use broadcasting to multiply this list by each column in the monthly_sales array. The monthly_sales array is loaded, along with numpy as np.

##### Ejercicio 5.1 - Broadcasting a lo largo de columnas

Se dispone de una lista llamada *valoresCrecimiento* de len() igual a 12. Esta lista representa el crecimiento esperado mes a mes para las industrias vistas en el ejercicio 4.

- Convierta la lista *valoresCrecimiento* en un array llamado *crecimientoMensual* de tal manera que se pueda calcular el crecimiento de un año al otro de las industrias del ejercicio 4. Para esto, deberá multiplicar *ventasAnuales* con *crecimientoMensual* y almacenar el resultado en un array llamado *ventasEsperadas*.
- Imrpima por pantalla el crecimiento esperado para la industra de bebidas.

In [24]:
valoresCrecimiento = [1.01, 1.03, 1.03, 1.02, 1.05, 1.03, 1.06, 1.04, 1.03, 1.04, 1.02, 1.01]
crecimientoMensual = ___
ventasEsperadas = ___

##### Ejercicio 5.2 - Broadcasting a lo largo de filas

En el ejercicio 4.4 se utilizó una lista llamada *listaMulti* la cual contenía los valores con las proyecciones de ventas mes a mes para las industrias. Supongamos que no confiamos plenamente en estas estimaciones. Entonces lo que haremos es encontrar un multiplicador *promedio* de posibles ventas para cada industria a partir de los datos dentro de *listaMulti* del ejercicio 4.4. Luego utilizaremos estos promedios para proyectar las ventas del próximo año.

In [25]:
listaMulti =   [[0.98, 1.02, 1.],
               [1.00, 1.01, 0.97],
               [1.06, 1.03, 0.98],
               [1.08, 1.01, 0.98],
               [1.08, 0.98, 0.98],
               [1.1 , 0.99, 0.99],
               [1.12, 1.01, 1.  ],
               [1.1 , 1.02, 1.  ],
               [1.11, 1.01, 1.01],
               [1.08, 0.99, 0.97],
               [1.09, 1.  , 1.02],
               [1.13, 1.03, 1.02]]

- Guarde en un array llamado *multiplicadoresPromedios* los valores medios correspodientes a las proyecciones de ventas para cada industria a lo largo de todo un año a partir de *listaMulti*.
- Imprima las *shapes* de *ventasAnuales* y *multiplicadoresPromedios* para corroborar que puedan ser broadcastables.

In [26]:
multiplicadoresPromedios = ___

- Multiplique cada venta mensual por los multplicadores promedios de cada industria. Almacene el resultado en array llamado *ventasProyectadas*.

In [27]:
ventasProyectadas = ___

<hr style="border:1px solid #16C79A"> </hr>

## <span style='color:#16C79A'>6. Trabajando con imagen del pintor Monet</span>

A continuación trabajaremos con una pintura del pintor [Monet]((https://es.wikipedia.org/wiki/Claude_Monet)).

- Carge el archivo *pintura.npy* -que es una foto RGB- que se encuentra dentro de la carpeta *files* en un arary llamado *monet*.

In [28]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
    
# ## Descomentar para ver la imágen cargada
# plt.imshow(monet)
# plt.show()

- Oscurezca la imágem *monet* en un 50%. Guarde el resultado en un array llamado *monetOscuredido*.

In [29]:
monetOscuredido = ___

# ## Descomentar para ver la imágen cargada
# plt.imshow(monetOscuredido)
# plt.show()

- Tome cada canal de *monet* y guardelos en tres arrays diferentes llamados *canalRojo*, *canalVerde* y *canalAzul*.



In [30]:
canalRojo = ___
canalVerde = ___
canalAzul = ___

In [31]:
# ### Descomente para ver los canales
# ceros = np.zeros((monet.shape[0],monet.shape[1])).astype(np.int8)
# fig = plt.figure()
# ax = fig.add_subplot(1, 3, 1)
# imgplot = plt.imshow(np.stack([canalRojo,ceros,ceros],axis = 2))
# ax.set_title('Canal Rojo')
# ax = fig.add_subplot(1, 3, 2)
# imgplot = plt.imshow(np.stack([ceros,canalVerde,ceros],axis = 2))
# imgplot.set_clim(0.0, 0.7)
# ax.set_title('Canal Verde')
# ax = fig.add_subplot(1, 3, 3)
# imgplot = plt.imshow(np.stack([ceros,ceros,canalAzul],axis = 2))
# imgplot.set_clim(0.0, 0.7)
# ax.set_title('Canal Azul')

In [32]:
# ### Descomente para ver los canales
# ceros = np.zeros((monet.shape[0],monet.shape[1])).astype(np.int8)
# fig = plt.figure()
# ax = fig.add_subplot(1, 3, 1)
# imgplot = plt.imshow(np.stack([canalRojo,canalRojo,canalRojo],axis = 2))
# ax.set_title('Canal Rojo')
# ax = fig.add_subplot(1, 3, 2)
# imgplot = plt.imshow(np.stack([canalVerde,canalVerde,canalVerde],axis = 2))
# imgplot.set_clim(0.0, 0.7)
# ax.set_title('Canal Verde')
# ax = fig.add_subplot(1, 3, 3)
# imgplot = plt.imshow(np.stack([canalAzul,canalAzul,canalAzul],axis = 2))
# imgplot.set_clim(0.0, 0.7)
# ax.set_title('Canal Azul')

- A partir del array *monet* tome el canal azul y calcule la media de píxeles.
- Reemplace todos los valores por encima de la media con 255.
- Forme un nuevo array monet llamado *monetResaltado* que este compuesto por los canales rojo y verde originales y el azul modificado.

In [33]:
mediaAzul = ___
monetResaltado = ___

In [34]:
# ### Descomente para ver monetResaltado
# plt.imshow(monetResaltado)
# plt.show()

<hr style="border:1px solid #16C79A"> </hr>

## <span style='color:#16C79A'>7. Buscando la inversa de una matriz</span>

Genere una función que reciba una matriz cuadrada como un *numpy.array* y retorne la inversa de la matriz. En el caso de que la matriz no tenga inversa, la función debe retornar None. 

<hr style="border:1px solid #16C79A"> </hr>

## <span style='color:#16C79A'>8. Profundizando el análisis del *Tree Census*</span>

Tomando el set de datos *treeInfo* responda,

- ¿Cuantos arboles vivos tenemos en el set de datos?
- ¿Cuantos arboles cortados tenemos en el set de datos?
- ¿Cual es el diámetro promedio de arboles vivos? ¿Y su desvío estándar? Agregue dos columnas al array original que contenga la media y el desvío estándar de los diametros de los troncos de arboles vivos.
- Cual es el diámetro promedio de arboles cortados? ¿Y su desvío estándar? Agregue dos columnas al array original que contenga la media y el desvío estándar de los diametros de los troncos de arboles cortados.

Utilice lo visto hasta acá para buscar en el set de datos lo que se pide en el ejercicio.

In [35]:
## ToDO Ejercicio 6